# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Kaajol Dhana/Desktop/lab6/lab6.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/clk_disp.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/clk_div.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/decrement.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/decrement_val.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/increment.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/increment_val1.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/stopwatch_mux.v}
  {C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/sources_1/new/stopwatch_main.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/constrs_1/imports/lab6/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Kaajol Dhana/Desktop/lab6/lab6.srcs/constrs_1/imports/lab6/Basys3_Master.xdc}}]


synth_design -top stopwatch_main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef stopwatch_main.dcp

catch { report_utilization -file stopwatch_main_utilization_synth.rpt -pb stopwatch_main_utilization_synth.pb }
